import "@/css/login.css";
import Providers from "@/redux/Provider";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <Providers >
    <html lang="en">
      <body>
       
        {children}
      </body>
    </html>
    </Providers>
  );
}
