import "@/css/globals.css";
import Footer from "@/components/Footer";
import Header from "@/components/Header";
import Providers from "@/redux/Provider";
import { Suspense } from 'react'
// import redux


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <Providers>
    <Suspense>
    <html lang="en">
      <body>
         <Header/>
         {children}
          <Footer/>
        

      </body>
    </html>
    </Suspense>
    </Providers>
  );
}
